### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by random-robbie** [MisterPhilip/x-forwarded-for#1]
Hi Dude,

This addon is perfect for what i needed.

Are you planning to release one for X-Real-IP at all or would you have any issues if i changed the code and released it doing X-Real-IP but with full credits to you?

This addon has been well received by some of my followers on twitter who will be using it for testing security on some bug bounty planforms.

https://twitter.com/Random_Robbie/status/920622185898704896

**Comment by MisterPhilip** [comment]
At this time I don't plan on releasing a X-Real-Ip, so feel free to fork away. Glad you're able to use the addon!

**Comment by random-robbie** [comment]
perfect just thought i would ask.

Found it handy for bypassing some geo-restrictions on some streaming servers.

I will link once completed 👍

**Comment by jacob755** [comment]
question is that addon add privacy and security value for user?
please explain it for newbie 
thanks
