### ISSUE TITLE
Can this be used to bypass the X-Frame-Options SAMEORIGIN header?

### ISSUE THREAD

**Issue by E3V3A** [MisterPhilip/x-forwarded-for#10]
I'm look for an alternative tool to bypass the **X-Frame-Options** `SAMEORIGIN` header.

There used to be the tool: https://github.com/niutech/x-frame-bypass 
but it's no longer being maintained/working and doesn't work in the same way, anyway. 

Can I use or modify your tool to do this?

**Comment by MisterPhilip** [comment]
If you're just wanting to add the X-Frame-Options header, I'd suggest looking at using any of these:

- https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en
- https://chrome.google.com/webstore/detail/modify-headers-for-google/innpjfdalfhpcoinfnehdnbkglpmogdi?hl=en-US
- https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en

But, if you're wanting to inject content in the page I'd say that would be out of scope for this extension. You're free to fork/develop as you see fit for your needs (MIT License)! 😄

**Comment by E3V3A** [comment]
Hi @MisterPhilip !  Thanks for quick response. 

> suggest looking at ...

I'm not using Chrome, but FF...

> if you're wanting to inject content

No, I don't really need to inject anything (today). All I'm trying to do is add some remote iframe content to an old HTML page without a server. (Was hoping to avoid having to run a server, even if that is perhaps the best way way.)

**Comment by MisterPhilip** [comment]
> All I'm trying to do is add some remote iframe content to an old HTML page without a server.

Sounds like you're wanting to inject content into the page then. I'd suggest either just manually doing it with the developer tools or using an extension such as https://addons.mozilla.org/en-US/firefox/addon/codeinjector/. Unfortunately, that sort of feature would be out of scope for this extension.
