### ISSUE TITLE
Support for multiple IP addresses

### ISSUE THREAD

**Issue by mcattle** [MisterPhilip/x-forwarded-for#11]
This extension has been great for basic X-Forwarded-For testing, but the spec for that header allows for multiple addresses, in a comma+space delimited list.  I'd like to request a feature to allow for multiple IP addresses in the X-Forwarded-For header tag.

**Comment by MisterPhilip** [comment]
Sorry this took so long to get out, @mcattle! But you should be seeing this with 0.6.0, which is rolling out now.
