### ISSUE TITLE
CORS issue with wordpress

### ISSUE THREAD

**Issue by FireMasterK** [MisterPhilip/x-forwarded-for#14]
Access to font at 'https://fonts.gstatic.com/s/materialiconsoutlined/v21/gok-H7zzDkdnRel8-DQ6KAXJ69wP1tGnf4ZGhUce.woff2' from origin 'https://redacted' has been blocked by CORS policy: Request header field x-forwarded-for is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by MisterPhilip** [comment]
This is a CORS issue with the server - not the extension. The `Access-Control-Allow-Headers` needs to have `X-Forwarded-For` included for you to use the extension properly.

**Comment by MisterPhilip** [comment]
Thanks for the PR - I've submitted to both Chrome/Firefox extension stores. FF should be out already, Chrome usually takes several days to review before it's published.

**Comment by FireMasterK** [comment]
Awesome!
