### ISSUE TITLE
Default ip value

### ISSUE THREAD

**Issue by tonysader** [MisterPhilip/x-forwarded-for#17]
Hello, @MisterPhilip  thanks for this great extension.
I need this extension for some automation tests using selenium and geckodriver  so I need to fork it and make a default value..
Can you help me with this, please? Thanks

**Comment by MisterPhilip** [comment]
If you're building it locally, you can just update the eventPage script to include a default IP (`spoofIp`) at the top:
https://github.com/MisterPhilip/x-forwarded-for/blob/master/src/eventPage.js#L3

I'm sure there is a way to set options with selenium + geckodriver/chromedriver, but I haven't dug too much into those lately.

**Comment by tonysader** [comment]
> If you're building it locally, you can just update the eventPage script to include a default IP (`spoofIp`) at the top:
> https://github.com/MisterPhilip/x-forwarded-for/blob/master/src/eventPage.js#L3
> 
> I'm sure there is a way to set options with selenium + geckodriver/chromedriver, but I haven't dug too much into those lately.

Hey,
I didn't find a way to do it on selenium but I've updated the javascript file and it worked.
Thanks for the tool it is very helpful, and I am sorry for not labeling the issue as a question before.
