### ISSUE TITLE
add more allowedHeaders 

### ISSUE THREAD

**Issue by Mr-xn** [MisterPhilip/x-forwarded-for#24]
hi,man
thank u work for this useful plugins.i have some idear.
add more `allowedHeaders` like these:
```json
["x-forwarded-for", "x-real-ip", "x-forwarded", "forwarded-for", "forwarded", "true-client-ip", "client-ip", "ali-cdn-real-ip", "cdn-src-ip", "cdn-real-ip", "cf-connecting-ip", "x-cluster-client-ip", "wl-proxy-client-ip", "proxy-client-ip", "true-client-ip"]
```
i think the best ways is user can add,del or change it by themslef.

**Comment by MisterPhilip** [comment]
Added! It is pending release in the stores but the list has been updated in 19e5d45.
