### ISSUE TITLE
Wrong icon on enable

### ISSUE THREAD

**Issue by aarubui** [MisterPhilip/x-forwarded-for#38]
@MisterPhilip
When the extension gets enabled (by disabling then enabling or by closing Chrome completely and reopening), the icon is `logo-*-bw.png` (as defined in `manifest.json`). Adding `updateFromSettings()` to `serviceWorker.ts` (not inside any callbacks) seems to work but I'll let you figure it out properly.

**Comment by MisterPhilip** [comment]
Thanks, I noticed this occasionally when testing but bumped the priority down. Will dig into it more.

**Comment by basselkhaddour** [comment]
Sir, please help, they have updated sites and are no longer working on them, Please solve the problem and contact me on Telegram (https://t.me/samuelzion)
 I will give you a financial reward if it is solved on
https://www.swagbucks.com
https://www.mypoints.com
https://www.inboxdollars.com
![Screenshot 2024-06-01 042741](https://github.com/MisterPhilip/x-forwarded-for/assets/43155107/d45caf3b-69a2-42be-9a7f-afc6582ca4c6)

**Comment by MisterPhilip** [comment]
Thanks @aarubui for your help here! I appreciate you being patient and helpful with your feedback.

I've published the changes that should fix this in v1.0.2, which is pending release in the Chrome webstore.
