### ISSUE TITLE
Bug: Domain Scope Changes from 'Exclude' to 'Include' After Saving

### ISSUE THREAD

**Issue by fany0r** [MisterPhilip/x-forwarded-for#44]
Hi, man, thanks for this great extension!

I found an issue while using it. When editing an existing config file (scope: all domains except the ones listed below), after clicking save, it changes to "for the following domains".

I need to edit it again and select "Exclude" to make it work properly.

![action1](https://github.com/user-attachments/assets/08b61e43-4f06-4159-9a6b-58d150bf987d)

**Comment by MisterPhilip** [comment]
Thanks, good catch! I'll take a look

**Comment by fany0r** [comment]
@MisterPhilip Hi man ,

I hope you are well. I recently submitted a PR to fix it. Could you please take a moment to review it when you have a chance? Thank you!

**Comment by MisterPhilip** [comment]
Sorry this took so long to get back to - life has been busy. I appreciate you creating a pull request for this! I will be uploading it to the extension store today so hopefully they have a quick turnaround.
