### ISSUE TITLE
Firefox version 0.4.0 release?

### ISSUE THREAD

**Issue by acebece** [MisterPhilip/x-forwarded-for#7]
I was going to suggest adding a recently used IPs feature when I noticed that you already implemented such in the 0.4.0 version.

Any reason why you did not release that version for Firefox?

P.S.: On addons.mozilla.org the extension is called `X-Forwarded-For Injector` whereas in the manifest it says `X-Forwarded-For Header`. You may want to fix that to prevent someone from hijacking the name.

**Comment by MisterPhilip** [comment]
Huh, I'm honestly not sure why I never released it on Firefox. I'll see if I can do that later today.

And thanks for the heads up - I'll make the change!

**Comment by MisterPhilip** [comment]
This has been released - usually propagates out within an hour. 

And for the name, there was previously a `X-Forwarded-For Header`, but it looks like it's no longer listed on the add-on store, so I've changed mine over to `X-Forwarded-For Header`. Thanks again or the heads up :+1:

**Comment by acebece** [comment]
Thanks, much appreciated.
