### ISSUE TITLE
Only for certain domains?

### ISSUE THREAD

**Issue by guilheb** [MisterPhilip/x-forwarded-for#8]
Hello,

Very useful extension. My work flow is that I am using the web browser on my local machine, but actually programming with PhpStorm on another machine through a Remote Desktop connection. Your extension allows me to forward the Xdebug debugging session to the remote machine. It works great.

For privacy reasons, it would be nice if the X-Forwarded-For header would only be sent for pages I visit on my domains.

**Comment by MisterPhilip** [comment]
Great to hear the extension has been useful for you!

Right now, you could clear out the value when you visit a domain that isn't one you want to send a header for. Then the most recent IP would show in the list to easily send it again. However, I see the use in your use case. Do you have any suggestions or preferences on how you'd like to see that configured?

**Comment by guilheb** [comment]
Personally, I don't need anything more fancy than simply a list of 
allowed domains. Thanks for getting back.

**Comment by jacob755** [comment]
question is that addon add privacy and security value for user?
please explain it for newbie 
thanks

**Comment by MisterPhilip** [comment]
Added! It is pending release in the stores but the list has been updated in 19e5d45.
